/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ice_jni_registry_RegistryKey */

#ifndef _Included_com_ice_jni_registry_RegistryKey
#define _Included_com_ice_jni_registry_RegistryKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    openSubKey
 * Signature: (Ljava/lang/String;I)Lcom/ice/jni/registry/RegistryKey;
 */
JNIEXPORT jobject JNICALL Java_com_ice_jni_registry_RegistryKey_openSubKey
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    connectRegistry
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/ice/jni/registry/RegistryKey;
 */
JNIEXPORT jobject JNICALL Java_com_ice_jni_registry_RegistryKey_connectRegistry
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    createSubKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Lcom/ice/jni/registry/RegistryKey;
 */
JNIEXPORT jobject JNICALL Java_com_ice_jni_registry_RegistryKey_createSubKey
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    closeKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ice_jni_registry_RegistryKey_closeKey
  (JNIEnv *, jobject);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    deleteSubKey
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ice_jni_registry_RegistryKey_deleteSubKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    deleteValue
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ice_jni_registry_RegistryKey_deleteValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    flushKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ice_jni_registry_RegistryKey_flushKey
  (JNIEnv *, jobject);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    getValue
 * Signature: (Ljava/lang/String;)Lcom/ice/jni/registry/RegistryValue;
 */
JNIEXPORT jobject JNICALL Java_com_ice_jni_registry_RegistryKey_getValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    setValue
 * Signature: (Ljava/lang/String;Lcom/ice/jni/registry/RegistryValue;)Z
 */
JNIEXPORT void JNICALL Java_com_ice_jni_registry_RegistryKey_setValue
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    getStringValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ice_jni_registry_RegistryKey_getStringValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    getDefaultValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ice_jni_registry_RegistryKey_getDefaultValue
  (JNIEnv *, jobject);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    hasDefaultValue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ice_jni_registry_RegistryKey_hasDefaultValue
  (JNIEnv *, jobject);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    hasOnlyDefaultValue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ice_jni_registry_RegistryKey_hasOnlyDefaultValue
  (JNIEnv *, jobject);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    getNumberSubkeys
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ice_jni_registry_RegistryKey_getNumberSubkeys
  (JNIEnv *, jobject);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    getMaxSubkeyLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ice_jni_registry_RegistryKey_getMaxSubkeyLength
  (JNIEnv *, jobject);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    regEnumKey
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ice_jni_registry_RegistryKey_regEnumKey
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    getNumberValues
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ice_jni_registry_RegistryKey_getNumberValues
  (JNIEnv *, jobject);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    getMaxValueDataLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ice_jni_registry_RegistryKey_getMaxValueDataLength
  (JNIEnv *, jobject);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    getMaxValueNameLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ice_jni_registry_RegistryKey_getMaxValueNameLength
  (JNIEnv *, jobject);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    regEnumValue
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ice_jni_registry_RegistryKey_regEnumValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    incrDoubleWord
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ice_jni_registry_RegistryKey_incrDoubleWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    decrDoubleWord
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ice_jni_registry_RegistryKey_decrDoubleWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ice_jni_registry_RegistryKey
 * Method:    expandEnvStrings
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ice_jni_registry_RegistryKey_expandEnvStrings
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
